#!/usr/bin/env Rscript

library(knitr)
library(markdown)

library(optparse)

option.spec = list(
    make_option(c("-v", "--verbose"), action="store_true", default=FALSE,
                help="print verbose output"),
    make_option(c("-s", "--spin"), action="store_true", default=FALSE,
                help="run output through spin"),
    make_option(c("-n", "--no-eval"),
                dest="eval", action="store_false", default=TRUE,
                help="do not evaluate R code")
)

cli = parse_args(OptionParser(option_list=option.spec, prog="Rnit"),
    positional_arguments=1)
opts = cli$options

if (opts$verbose) {
    opts_knit$set(verbose=TRUE)
}
if (!opts$eval) {
    opts_chunk$set(eval=FALSE)
}

for (arg in cli$args) {
    if (opts$spin) {
        message("Spinning ", arg)
        rmd.file <- spin(arg, knit=FALSE)
    } else {
        rmd.file <- arg
    }
    message("Knitting ", rmd.file)
    md.file <- knit(rmd.file, envir=new.env())
    message("Rendering ", md.file)
    markdownToHTML(file=md.file, out=gsub("\\.md$", ".html", md.file))
}
